### ISSUE TITLE
Support for React 0.13

### ISSUE THREAD

**Issue by khoerling** [omniscientjs/omniscient#102]
Is this on the roadmap, or?

**Comment by mikaelbr** [comment]
React 0.13 is supported? Are you running into any issues?

**Comment by khoerling** [comment]
Pardon my tardiness replying, Omniscient works fine with React 0.13!  My issue was with combining react-router-component and Omniscient.  I had to use the .jsx method to get at the class

**Comment by eggsby** [comment]
Hm, 0.13 doesnt work for me - I am getting "Can't add property context, object is not extensible"

- My little app:

```js
var React = require('react'),
    immstruct = require('immstruct'),
    component = require('omniscient');

var struct = immstruct({
  greeting: "Hello from js"
});


var View = component('View', ({greeting}) => (
  <h1>
    {greeting.deref()}
  </h1>
));

function render() {
  React.render(
    React.createElement(View, { greeting: struct.cursor('greeting') }),
    document.getElementById('content')
  );
}

render();
struct.on('swap', render);
```

Changing to react 0.12 works fine.

**Comment by torgeir** [comment]
You didn't by any chance miss `.jsx` as well?

```js
var View = component('View', ({greeting}) => (
  <h1>
    {greeting.deref()}
  </h1>
)).jsx;       // <--
```

It's a shame that this is neacessary, but it is since 13. Or you can enable it for the whole of the `component` you require like

```js
var component = require('omniscient').withDefaults({ jsx: true });
```

**Comment by mikaelbr** [comment]
Actually, if you don't want to use JSX you don't have to do `.jsx` or set `jsx` to true by default. You can easily do Render directly on the invocation of your View component, as it is a ready made element. 

Omniscient components by default work like functions, instead of classes as with React. They return elements which can be used directly as children or be rendered. 

So doing 

```js
function render() {
  React.render(
   View({ greeting: struct.cursor('greeting') }),
    document.getElementById('content')
  );
}
```

Should work as expected. The only time you need to think about `.jsx` or `jsx: true`, is if you want to use Omniscient Components as JSX/React Classes:

If you wanted to use `View` with JSX in `App`, would require `.jsx`:

```jsx
// This whouldn't work
var App = component(({greeting}) => <View greeting={greeting} />);

// Unless you did 
var App = component(({greeting}) => <View.jsx greeting={greeting} />);
// Or
var ViewClass = View.jsx;
var App = component(({greeting}) => <ViewClass greeting={greeting} />);

// Or had all your components as JSX-elements:

var omniscient = require('omniscient');
var jsxComponent = omniscient.withDefaults({ jsx: true });

var View = jsxComponent(/* .. */)
// This would now work
var App = component(({greeting}) => <View greeting={greeting} />);
// But not 
var App = component(({greeting}) => View({greeting}));
```
