### ISSUE TITLE
[question] strategy to avoid local state clutter?

### ISSUE THREAD

**Issue by kswope** [omniscientjs/omniscient#108]
It the docs it says 

>
You are free to this.setState({ .. }) for component local view state, but it is highly encouraged to avoid using local state where this is possible.

But it my mind just throwing all your local state garbage in the main pile is going hurt the same as using global variables.  Does anybody have a good suggestion for this problem?

**Comment by torgeir** [comment]
We should probably rephrase that - for some things component local state makes total sense. I wouldn't want to clutter my data with stuff that *belongs* in the view, e.g. an inline editors state being in edit-mode or not

**Comment by kswope** [comment]
I don't know.  Are we sure about that?  If you put all state in the main state can components hot swap without resetting the local data and do we care?

**Comment by kswope** [comment]
Stumbled across the Todo app example linked from this repo, it uses immstruct for local state.  Its nice and clean but I can't tell if its the proper way to do things.  There's an ugly  'nextTick' in all its 'actions', which might be related.  The example is out of date and doesn't even run because it requires 6to5.

It looks to me that if you keep local state in the immstruct, you can avoid all the business of setState, getInitialState, mixins, etc and a lot of the reactjs is factored out - do I have that right or is there a catch?  Do we end up with rendering artifacts like flickering?

https://github.com/jcranendonk/todomvc-omniscient/blob/master/src/js/action.js

**Comment by mikaelbr** [comment]
> I don't know. Are we sure about that? If you put all state in the main state can components hot swap without resetting the local data and do we care?

As boring answer as this is: I think it depends. Something can make "more sense" to have as local state. Things that doesn't have implications for the rest of your application, and isn't all that necessary to be reproducible from global app state. This can be things like additional styling classes, some toggle functionality, etc. But you can definitely have this kind of state in global as well.

I have done projects with something like accordion constructs where the expanded/contracted state is global. That made more sense for that project, instead of having it as a local state.

>  Stumbled across the Todo app example linked from this repo, it uses immstruct for local state. Its nice and clean but I can't tell if its the proper way to do things. There's an ugly 'nextTick' in all its 'actions', which might be related. The example is out of date and doesn't even run because it requires 6to5.

As far as I can see, the `nextTick` here is just to make updating immstruct structures async, as they are per default sync. It shouldn't be necessary, but it is a neat trick for making callback given to `on('swap')` async.

> It looks to me that if you keep local state in the immstruct, you can avoid all the business of setState, getInitialState, mixins, etc and a lot of the reactjs is factored out - do I have that right or is there a catch? Do we end up with rendering artifacts like flickering?

> https://github.com/jcranendonk/todomvc-omniscient/blob/master/src/js/action.js

AFAIK, there is no immediate "catch" for having your state as global state. One thing to think about is if you have high frequent updates and a large component/data tree and your changes is "far down the tree", it can cause many objects being created and you will probably see the garbage collector do a lot of work. If that is the case, it might make sense to "localise" the update/render-loop. I think, for the most cases it'll do with a global state, though. And for the projects I've done, this limitation hasn't been met yet.

**Comment by torgeir** [comment]
> AFAIK, there is no immediate "catch" for having your state as global state.

..other than that your conflating your view state with your data :)

**Comment by mikaelbr** [comment]
Sure. It depends on what you define as view state or not. But, yes, there is such a thing as view state that shouldn't necessarily be defined in the "global" space.
