### ISSUE TITLE
react-router and <Link> don't work together

### ISSUE THREAD

**Issue by kswope** [omniscientjs/omniscient#109]
Of all the example of making react-router and omniscient work together I haven't seen one that uses 

```
<Link to='path'>
```

I made an example here https://github.com/kswope/omni-nested-routes-linkto-demo

The only difference between the working example and the dysfunctional example is that one uses
React.createClass and the other uses omniscient components

Link doesn't trigger a redrawing but it does change the url.  Setting shouldComponentUpdate always return true fixes the problem, but you know.

Any help appreciated, and maybe update the demo repo https://github.com/omniscientjs/omniscient-react-router.  The demo seems to work with nested routes only because the counter continuously causes redraws.

**Comment by torgeir** [comment]
Hi,

This is not because you're using `<Link to>`, but rather because you're attempting to re-render components whose `shouldComponentUpdate` always return false, because their input has not changed/there are no inputs - and omniscient's primary goal is *not to rerender when components' inputs don't change*. You will however  always get the initially rendered version of all components, so it does work as you'd expect if you access e.g. `/#/lust/gluttony/greed` directly.

This works with plain react components as [they default to always re-render when a user defined `shouldComponentUpdate` is not present](https://github.com/facebook/react/blob/master/src/renderers/shared/reconciler/ReactCompositeComponent.js#L547-L550).

To work around this with your omnsicient components you will need to override `shouldComponentUpdate` to return true. This is really no different than how it works for plain react components. If you intend to use omniscient's ability to rerender only when passed data has changed for components in other places you're probably better off doing this on a component basis rather than for your whole `component` instance. 

```js
let alwaysRerender = { shouldComponentUpdate: () => true };

var Limbo = component([alwaysRerender], () => (
   <div>
     {links()}
     <div className='levels'>
       <RouteHandler />
     </div>
   </div>);

var Lust = component([alwaysRerender], () => (
   <div>
     Lust
     <RouteHandler />
   </div>));

var Gluttony = component([alwaysRerender], () => (
   <div>
     Gluttony
     <RouteHandler />
   </div>));

var Greed = component([alwaysRerender], () => (
   <div>
     Greed
   </div>));
```

Hope that helps

**Comment by torgeir** [comment]
I've [updated the example to show how this works](https://github.com/omniscientjs/omniscient-react-router/commit/412c0ff855d54256d0a59f4845581217bbef74d5). Let us know if things still are not working out!

**Comment by kswope** [comment]
I'm just getting started with React.js so I'm a little clueless, so I hope you forgive that. 

Is the above solution ideal or is it a kludge?  If you have a top level route that always renders does it mean everything always renders when anything changes or does the rerendering happen only when you browse to another route so its not a big deal?  As great as omnicient is, is it just fundamentally incompatable with react router?

**Comment by Dashed** [comment]
The gist of the problems are outlined here: https://github.com/facebook/react/issues/2517

Contexts in react are an undocumented feature; but various 3rd-party libraries extensively rely on them (react-router for example).

A solution would be that omniscient should detect the new contexts passed as `nextContext` in the 3rd argument: `shouldComponentUpdate: function(nextProps, nextState, nextContext)`; and re-render as necessary.

-----

react-router relies the user to re-render the root component in a **true** top-down component rendering approach. This is necessary for contexts to be appropriately updated, and therefore the react-router components to function properly. 

As a consequence, you cannot optimize towards sub-tree re-rendering.

I decided to ditch react-router until contexts are more matured.

For the time being, I kept things simple by using a router agnostic library: https://github.com/visionmedia/page.js
Then bundle it with [immstruct](https://github.com/omniscientjs/immstruct); and have any components listen to the route cursor.

**Comment by kswope** [comment]
@Dashed 

Grrr, every time I give up on omniscient, pick out my perfect flux library (again) and get to work, somebody teaches me something and I go back to omniscient.  Its like this library has a gravitational pull.

**Comment by gaearon** [comment]
`react-router@3.0.0-alpha.1` fixes this issue.

**Comment by mikaelbr** [comment]
Thanks for letting us know, @gaearon !
