### ISSUE TITLE
Class API

### ISSUE THREAD

**Issue by polkovnikov-ph** [omniscientjs/omniscient#117]
I would like to use `omniscient` with `radium`. The problem is that `Radium` is a class decorator, and it cannot be applied to an already created component. The obvious hack is to apply `Radium` [here](https://github.com/omniscientjs/omniscient/blob/master/component.js#L144), but I'm quite uneasy with it.

Is there a way to use `omniscient` with classes? (From the source code it seems the answer is "no" currently)

Do you have any plans on implementing such an API?

I think I could manage getting `React.createElement` out of the `factory()` and make it into a pull request. What do you think a proper API for classes would look like?

```javascript
// Fails later with "React component classes must extend React.Component."
var Item = Radium(component(({item}) => <div>
	{item.get('text')}
	<button onClick={setText.bind(this, item)}>Set text</button>
</div>));

var Test = Radium(component(({array}) => <div>
	{array.map((item) =>
		<Item item={item} key={item.get('id')} />
	)}
</div>));

var c = 0;
function setText(item, e) {
	item.set('text', '' + (c++));
}

var structure = immstruct([
	{id: 0, text: 'A'},
	{id: 1, text: 'B'},
	{id: 2, text: 'C'},
	{id: 3, text: 'D'},
]);
var mountPoint = document.getElementById('react');
structure.on('swap', render);
function render() {
	debugger;
	ReactDOM.render(<Test array={structure.cursor()} />, mountPoint);
}
render();
```

**Comment by mikaelbr** [comment]
With the current version of Omniscient (`v3.2.0`) you could have done this by doing:

```js
var MyComponent = Radium(MyOmniscientComponent.jsx);
```

As `jsx` has the React "Class" exposed, however, with the latest React 0.14 this is no longer needed for JSX non JSX-interop, so it is removed

I haven't run into this need my self, but is there many implementations that use class specific decoration/modification instead of component based?

One possible API extension could be a decoration applyer of some sort:

```js
var decorators = compose(Radium, SomeOther);
var MyComponet = component.withDecorators(decorators, function () {
  // <div> ...
});
```

And instead of [line 144](https://github.com/omniscientjs/omniscient/blob/master/component.js#L144) it would something in the lines of:

```js
var Component = (decorators || identity)(React.createClass(componentObject));
```

But I don't know if this is a needed extension, or is "class level" decorator just something that is exclusively used by Radium?


Another option, is to create the class your self, but use the `shouldComponentUpdate` provided by Omniscient:


```js
var scu = require('omniscient/shouldupdate');

var MyComponent = Radium(React.createClass({
  shouldComponentUpdate: scu,
  render: function () {

  }
});
```

**Comment by polkovnikov-ph** [comment]
As ES7 is in its long way to become a standard, currently there's not much decorator libraries. Though there will be a lot soon. I took a minimal approach with passing decorators via `decorate` option to `withDefaults`. I've applied a decorator in `if (...)`, so that identity function won't slow down execution and won't get into call stack.

I missed the last approach, though passing props via an argument to the function seems a beautiful idea to me. I wouldn't like to lose that syntax sugar.

**Comment by mikaelbr** [comment]
Thanks for your contributions and the PR. :cake: 

> As ES7 is in its long way to become a standard, currently there's not much decorator libraries. Though there will be a lot soon. I took a minimal approach with passing decorators via decorate option to withDefaults. I've applied a decorator in if (...), so that identity function won't slow down execution and won't get into call stack.

Decorators are not ES2016 specific, even though ES2016 adds a syntactic sugar to decorate method and `class` declarations. There is nothing stopping one from having [decoration as a pattern](https://github.com/omniscientjs/omnipotent#decorators) as of now. My question was more intended as are there many use cases for decorating the class instead of the element/component. It seems to me it would be more common to decorate components, and the cases where you want to alter the class declaration it self is less common.

> UPD. Well, even though I was careful, I've messed things up. This one applies Radium to every class, even when it's not needed. I'm not sure if everyone would like to do that.

This is why I thought of adding a `component.withDecorators` end point.
