### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by nomad5000** [omniscientjs/omniscient#119]
First:

Where can I ask questions about the use of omnicient, without having to create an issue here?

Second:
```javascript
let structure = immstruct({
    libs: [
    { title: 'Backbone.js', url: 'http://documentcloud.github.io/backbone/'}, 
    { title: 'something.js', url: 'http://something.com'}, 
    ]
})


let cursor = structure.cursor()
console.log(structure.cursor().get('libs').toArray());
let tmp = cursor.get('libs').push({tile:"test",url:"test.com"})
console.log(structure.cursor().get('libs').toArray());
```

If I do this I get some behavior I don't quiet understand.

The first log prints [Keyedcursor,Keyedcursor] Ok An Array with two Keyedcursors That's as expected.

So far I understand.

The second log prints [KeyedCursor, KeyedCursor, Object]
The first two being the Keyedcursor exactly like the former log and the third being the Object I wanted to add to the list in libs. Why is it not transformed to a keyed cursor? I would expect that behavior. Is there a proper way to do this?

**Comment by mikaelbr** [comment]
Hi!

First: You can also ask questions on the Gitter channel: https://gitter.im/omniscientjs/omniscient, but asking here in the issues is also fine.

Second: This is due to how Immutable.js works. It doesn't decide for you if you should only use immutable structures or mutable objects. What you do is push a normal javascript object into an immutable object, so you have an array of two cursors and one object.

Instead you could do something like:

```js
let tmp = cursor.cursor('libs').push(Immutable.Map({tile:"test",url:"test.com"}));
```


By doing this instead, you will update your underlying list (that the cursor is pointing to), and add a new element that is a immutable map.

You can read more about Immutable.js in their docs: http://facebook.github.io/immutable-js/ or feel free to ask more questions if something is unclear.

**Comment by aknuds1** [comment]
Great stuff Mikael ;) I was wondering about this too...
