### ISSUE TITLE
Example of debounce the onChange for controlled form inputs

### ISSUE THREAD

**Issue by dendril** [omniscientjs/omniscient#37]
Could be possible for you to add an example of a debounce situation, but using omniscient instead of plain react code?

I'm trying to create a simple search component with a debounce of 300ms before fires the updates on the immstruct, and seems I'm losing something in the middle.

Thanks for your time :smile:

**Comment by Dashed** [comment]
IMO, I abstract out immstruct code away from components. I wasn't comfortable mixing immstruct logic into components, especially when complexity increases. Then I use a simple flux architecture (based on reflux), with functions (belonging to a store object) bound to actions.

Then it's easy to implement debounce at store function level; rather than worrying about rate-limitting on user events at React component level (in fact, I think we shouldn't be doing this :smile:).

**Comment by mikaelbr** [comment]
I think abstracting the data manipulation part of the code is a smart move. Not only for doing something like debouncing, but also for testability. Having something similar to `actions` (simply extracted cursor manipulative functions to a separate module), you can more easily test logic. 

```js
// search-actions.js
module.exports = function (cursor, input) {
   // do something with cursor
  return newCursor;
};
```

```js
// search-actions-test.js

var test = require('tap').test
test('do something with cursor', function (t) {
   var cursor = immstruct({ text: '' }).cursor('text');
   t.equal(action(cursor, 'foo').deref(), 'foo');
});
```

**Comment by dendril** [comment]
Then the idea is:
1- Keep the UI updated using the cursor I provide at creation time (default behavior).
2- Use Flux or whatever to decouple the debounce behavior, but it should be somewhere else.

@Dashed I don't like any of the flux implementations :sob: I don't feel confortable on mixing functional with OO at all. That's why I love this project :smile:, I need to figure out a better way to express the flow, probably I'm going to investigate arrow finite state machines and make transitions promise oriented by default.

Thanks a lot guys!
