### ISSUE TITLE
Storing cursors in state

### ISSUE THREAD

**Issue by mikaelbr** [omniscientjs/omniscient#41]
By @Dashed
> Thinking on this some more, I think there can be more done with shouldComponentUpdate so that the comparison process is done uniformly on both props and state. At the moment, state just gets the isEqual treatment.

> Here's an example of putting a cursor in component's state:

> ```js
> var structure = immstruct({turtles: []});

> var TurtlesComponent = React.createClass({

>  componentWillMount: function() {
    this.setState({turtlesCursor: structure.cursor()}

>    structure.on('swap', () =>
      this.setState({turtlesCursor: structure.cursor()}));

>  },

>  onAddButtonClick: function(e) {
    this.state.turtlesCursor.updateIn('turtles', (turtles) => 
      turtles.push(e.target.turtle)
    );
  },

>  renderTurtleCount: function() {
    return <div>{this.state.turtlesCursor.deref().size}</div>;
    // or pass own sub-cursor to a child component...
  }

>});
```

**Comment by mikaelbr** [comment]
I really think this is an anti-pattern, and nothing Omniscient should support. This would cause decrease of predictability, and thus reliability.

If someone would want to do this, they would have to override `isEqualState` and set it to equal `isEqualProps`.

**Comment by Dashed** [comment]
In this situation, I don't think it's an anti-pattern since the component owns the structure reference (and therefore the root cursor). So in this scenario, it's more of "sub"-top-down strategy.

------

I brought up an issue previously (https://github.com/omniscientjs/omniscient/issues/21), but it was about storing cursor from props that's passed from parent. In this case, it would be an anti-pattern, since: http://facebook.github.io/react/tips/props-in-getInitialState-as-anti-pattern.html

------

With regards to the pattern where the component owns the structure instance, the idea originally came from this gist: https://gist.github.com/confiks/745d27f7308db1935eb9
In that gist, the author was using a hypothetical reflux-like store library to manage cursors.

I had argued that the "store" can already be delegated to `immstruct` (or a wrapper of `immstruct`). 

This is the original conversation (not much :disappointed:): https://news.ycombinator.com/item?id=8926402

------

At the moment, it's a thought experiment, and haven't really tried this pattern too much. I'm still mulling on it. 

You're right, one can override `isEqualState` and set it to equal `isEqualProps`.

**Comment by mikaelbr** [comment]
Would #42 be a better solution for this?

**Comment by Dashed** [comment]
I don't follow what you meant by better solution...

**Comment by mikaelbr** [comment]
Couldn't they achieve the same thing?

```js
var structure = immstruct({turtles: []});

var TurtlesComponent = React.createClass({
 mixins: forceUpdate(structure.cursor()),

 onAddButtonClick: function(e) {
    structure.cursor().updateIn('turtles', (turtles) => 
      turtles.push(e.target.turtle)
    );
  },

 renderTurtleCount: function() {
    return <div>{structure.cursor().deref().size}</div>;
    // or pass own sub-cursor to a child component...
  }

});
```

**Comment by Dashed** [comment]
Ah I see. It is possible. Though, I'm more comfortable delegating render change via `setState` than `forceUpdate`...

**Comment by mikaelbr** [comment]
I think the conclusion of this is to be left to the user, and not "endorse" it as core support. With commit 197564c63b4dacf3d72f0133174bbe2fd8bccb28 you can do the following:

```js
var component = omniscient.withDefaults({
   isEqualState: omniscient.shouldComponentUpdate.isEqualProps
});
```
