### ISSUE TITLE
ShouldComponentUpdate throws warnings when Immutable.JS objects are stored in state or props

### ISSUE THREAD

**Issue by skevy** [omniscientjs/omniscient#55]
This is slightly different issue than #41 - I don't want to store _cursors_ in state, just immutable objects instead of mutable ones.

Unfortunately, because somewhere in lodash's isEqual method, it uses the "length" property, which is going to be deprecated in a future version of Immutable.JS https://github.com/facebook/immutable-js/wiki/Upgrading-to-Immutable-v3#size-from-length, it throws a warning anytime the function is called with Immutable.JS objects.

I'm not sure what exactly can be done about this, off the top of my head. But I wanted to flag it as an issue and put it up for discussion, as I feel like it's kind of important that we support putting immutable objects in state and props.

P.S.: I'm of course aware that I could override shouldComponentUpdate to make it so that, if I'm consistent in using all Immutable values for any deep structures in my state/props, i could just do a shallow equal (or just use PureRenderMixin, I suppose). I just think it'd be nice to include support in this library seeing as we're encouraging the use of immutable data structures throughout the rest of the application.

**Comment by Dashed** [comment]
A `customizer` function is passed to lodash `isEqual` for bypassing comparisons on cursors:
 https://github.com/omniscientjs/omniscient/blob/54e9dbc893e0d8fb088632a49a73c0976a35ec8a/shouldupdate.js#L94-L102

Maybe something similar can be done to Immutable objects? We'd use the following to verify if two objects are Immutable objects: http://facebook.github.io/immutable-js/docs/#/Iterable/isIterable

Then maybe do equality checking using `immutable.is()`: http://facebook.github.io/immutable-js/docs/#/is

----

I'm wondering if this is something that can be baked in.

**Comment by skevy** [comment]
@torgeir @mikaelbr thoughts? I can assist in a fix, I just want to make sure I'm not spending time on something that you guys don't agree on.

I'm giving a talk at React DC on Tuesday, focused on immutability, flux and the ideas of Om (and thus, Omniscient), and would like to be able to say with confidence that you can use immutables in state and props :)

**Comment by torgeir** [comment]
Since we're already deep-equaling everything not a cursor, in both props and state, I agree we should probably handle passing immutable structures not wrapped in cursors as well.

> Then maybe do equality checking using immutable.is()

I still don't know if `Immutable.is()` is the way to go as Immutable.js states its a *value* comparison, when a *reference* comparison ought to be enough (as data indeed is immutable). 

```js
function range (to) {
  var arr = [];
  for (var i = 0; i < to; i++) arr.push(i);
  return arr;
}

var one = Immutable.List(range(1000000));
var two = Immutable.List(range(1000001));
console.time('.is()');
console.log(Immutable.is(one, two));
console.timeEnd('.is()');

var three = one.push(1);
console.time('reference');
console.log(one === three);
console.timeEnd('reference');
```

I notice that comparisons of equal structures are pretty fast with `.is()`, though, but I don't know how immutable.js handles this internally, we'd have to do some digging

**Comment by mikaelbr** [comment]
Results from the code above on my machine:

```
 false
.is(): 0.576ms
false
reference: 0.139ms
```

I think we should definitely get better support for Immutable data structures in props and statics. But I'm thinking maybe a simple `isImmutable` and a reference check should do it. A `customizer` for our `isEqual*` checks should do it quite nicely.

Thinking something like #40 would be handy in this case.

**Comment by mikaelbr** [comment]
Might have to do a check like this: https://github.com/omniscientjs/immstruct/blob/master/src/structure.js#L318-L330

So having this as it's own module might be good.

**Comment by Dashed** [comment]
@torgeir 
Okay, yeah you're right, reference equality is the way to go. This works assuming you're using Immutable methods directly to update the object, instead of replacing the entire state (which is an anti-pattern) with an entirely new Immutable object.

Regardless, it's cheaper to rerender everything even when the previous state seems to be the same in values with the new state.

Related: https://github.com/facebook/immutable-js/wiki/Immutable-as-React-state

**Comment by Dashed** [comment]
Ideally, we want this https://github.com/facebook/immutable-js/issues/317 without having install the entire immutable library.

**Comment by skevy** [comment]
@mikaelbr don't we kind of have a dependency on Immutable anyway because this lib is used with immstruct?

**Comment by mikaelbr** [comment]
For now, you can switch out `isCursor` and `unCursor` defaults and use Omniscient with different immutable libraries if you want. We have some sort of dependency, but not a hard one.
