### ISSUE TITLE
Support for ES 6 classes without mixins

### ISSUE THREAD

**Issue by newtack** [omniscientjs/omniscient#94]
I'd like to use React 0.13 with classes, which means that I wouldn't be using mixins. 

Dan Abromov has an article of how to use composition instead, https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750 and Ryan Florence shows an example of it for react-router : https://github.com/rackt/react-router/blob/master/examples/auth-flow/app.js#L43-L72

I'd like to do something like this with omniscient. Is this possible now (if so how?) or what would it require?

**Comment by mikaelbr** [comment]
The principal of Omniscient is to think of components more as functions instead of "classes" - focus on content and render instead. There is pretty much only one need for mixins now, and that is attaching behaviour on life cycle events, the rest you can do just as functions. 

That being said, there is no reason why you couldn't do the same as Dan Abramov with Omniscient, if that is what you want:

```js
function connectToStores(Component, stores, getStateFromStores) {
  const methods = {
    getInitialState() {
      return getStateFromStores(this.props);
    },
    componentDidMount() {
      stores.forEach(store =>
        store.addChangeListener(this.handleStoresChanged)
      );
    },
    componentWillUnmount() {
      stores.forEach(store =>
        store.removeChangeListener(this.handleStoresChanged)
      );
    },
    handleStoresChanged() {
      if (this.isMounted()) {
        this.setState(getStateFromStores(this.props));
      }
    }
  };
  return component(methods, function StoreConnection (props) {
   return <Component {...props} {...this.state} />;
  });
};
```

But I think you could avoid using "methods" (except the life cycle functions) here as well, by using higher order functions. For instance, you could do `store.removeChangeListener(handleStoresChangedOn(comp))`

Omniscient encourages using higher order components. See for instance https://gist.github.com/mikaelbr/9dfac0137f5baf294863 or https://gist.github.com/mikaelbr/48d483bb7d078cf34cb8

**Comment by torgeir** [comment]
Yes, omniscient won't work with classes out of the box, and its primary focus is on functions like @mikaelbr says. 

If classes is your goal, though, `shouldComponentUpdate` is the only crucial part and you should be able to do something like to reuse the mixin we bundle

```
var Component = somethingHigherOrder(class extends React.Component {
  shouldComponentUpdate () {
    return omniscient.shouldComponentUpdate.apply(this, arguments);
  }
  render () {
    return (
      <div></div>
    );
  }
});
```

**Comment by newtack** [comment]
Thanks!
